name: PRs and Branches

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - main
      - master
      - development

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        cfengine: ["lucee@5", "adobe@2021", "adobe@2023"]
        coldbox: ["coldbox@6", "coldbox@7"]
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: yes
          MYSQL_USER: megaphone
          MYSQL_PASSWORD: megaphone
          MYSQL_DATABASE: megaphone
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Set Up CommandBox
        uses: elpete/setup-commandbox@v1.0.0

      - name: Install dependencies
        run: |
          box install
          box config set modules.commandbox-dotenv.checkEnvPreServerStart=false
          box install ${{ matrix.coldbox }} --noSave

      - name: Migrate database
        run: |
          box install commandbox-migrations
          box migrate install
          box migrate up

      - name: Start server
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_NAME: megaphone
          DB_USER: megaphone
          DB_PASSWORD: megaphone
        run: box server start cfengine=${{ matrix.cfengine }}

      - name: Run TestBox Tests
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_NAME: megaphone
          DB_USER: megaphone
          DB_PASSWORD: megaphone
        run: box testbox run

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Set Up CommandBox
        uses: elpete/setup-commandbox@v1.0.0

      - name: Install CFFormat
        run: box install commandbox-cfformat

      - name: Run CFFormat
        run: box run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cfformat changes